# Generated by Django 4.2.3 on 2023-07-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_number',
            field=models.CharField(max_length=10),
        ),
    ]
