# Generated by Django 4.2.3 on 2024-01-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quizsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizSubmission',
            new_name='QuizSubmissions',
        ),
    ]
