# Generated by Django 4.1.10 on 2023-09-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customer_cust_mail_alter_customer_cust_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
