# Generated by Django 4.1.10 on 2024-02-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
