# Generated by Django 5.0.1 on 2024-02-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
