# Generated by Django 5.0.1 on 2024-02-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='owner',
        ),
    ]
