# Generated by Django 5.0.1 on 2024-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_venue_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goalbasedcare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=2)),
                ('task', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=550)),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('accepted_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
