# Generated by Django 5.0.1 on 2024-02-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_venue_image_goalbasedcare_image_completedtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
