# Generated by Django 5.0.1 on 2024-02-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_completeddtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteddTask',
        ),
    ]
