# Generated by Django 5.0.1 on 2024-02-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_completeddtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalbasedcare',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Task Attended'),
        ),
    ]
