# Generated by Django 5.0.1 on 2024-02-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_goalbasedcare_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalbasedcare',
            name='task_number',
            field=models.IntegerField(),
        ),
    ]
