# Generated by Django 5.0.1 on 2024-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_goalbasedcare_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalbasedcare',
            name='task_number',
            field=models.CharField(max_length=2),
        ),
    ]
