# Generated by Django 5.0.1 on 2024-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_goalbasedcare_task_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goalbasedcare2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=2)),
                ('task', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=550)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False, verbose_name='Task Attended')),
            ],
        ),
        migrations.CreateModel(
            name='Goalbasedcare3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=2)),
                ('task', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=550)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False, verbose_name='Task Attended')),
            ],
        ),
    ]
